# .github/workflows/build-and-deploy.yml
name: Build & Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "ws" ]     # ggf. anpassen
  workflow_dispatch:

# Für Pages-Deploys nötig:
permissions:
  contents: read
  pages: write
  id-token: write

# Verhindert parallele Pages-Deploys
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Passe das an: Angular 17+ legt i.d.R. nach dist/<app>/browser ab.
  # Trage hier deinen App-Ordnernamen ein (aus angular.json -> "defaultProject")
  NG_APP_NAME: webgambling
  # Für Project Pages:
  BASE_HREF: "/webgambling/"   # bei Custom Domain oder user.github.io: "/"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'    # LTS; ggf. auf deine Version anpassen
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Falls dein package.json kein "ng" Script hat, ersetze durch:
      # run: npx ng build --configuration production --base-href "${{ env.BASE_HREF }}"
      - name: Build Angular (production)
        run: |
          npm run build -- --configuration=production --base-href "${{ env.BASE_HREF }}"
          # Optional (wenn benötigt): --deploy-url "${{ env.BASE_HREF }}"

      # Upload des fertigen Build-Ordners als Pages-Artifact
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/${{ env.NG_APP_NAME }}/browser
          # Falls dein Output-Pfad anders ist, hier anpassen.

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  
